version: '3'

services:
  mysql_dev:
    image: mysql:8.0-oracle
    container_name: mysql_dev
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_DEV_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DEV_DATABASE}
      MYSQL_USER: ${MYSQL_DEV_USER}
      MYSQL_PASSWORD: ${MYSQL_DEV_PASSWORD}
    ports:
      - "${MYSQL_DEV_PORT}:3306"
    volumes:
      - mysql_dev_data:/var/lib/mysql

  mysql_testing:
    image: mysql:8.0-oracle
    container_name: mysql_testing
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_TESTING_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_TESTING_DATABASE}
      MYSQL_USER: ${MYSQL_TESTING_USER}
      MYSQL_PASSWORD: ${MYSQL_TESTING_PASSWORD}
    ports:
      - "${MYSQL_TESTING_PORT}:3306"
    volumes:
      - mysql_testing_data:/var/lib/mysql

  mysql_prod:
    image: mysql:8.0-oracle
    container_name: mysql_prod
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PROD_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_PROD_DATABASE}
      MYSQL_USER: ${MYSQL_PROD_USER}
      MYSQL_PASSWORD: ${MYSQL_PROD_PASSWORD}
    ports:
      - "${MYSQL_PROD_PORT}:3306"
    volumes:
      - mysql_prod_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "${ADMINER_PORT}:8080"

volumes:
  mysql_dev_data:
  mysql_testing_data:
  mysql_prod_data:
